channels:
  - conda-forge
  - nvidia
dependencies:
  - python
  - clang=16
  - clang-format=16
  - compiler-rt_linux-64
  - gcc_linux-64=12
  - gxx_linux-64=12
  - llvm-openmp
  - cuda-toolkit
  - cmake
  - ninja
  - lld=16
