name: TPP-MLIR Benchmarks

on:
  workflow_dispatch:
    inputs:
      RUN_SPR_BENCH:
        description: "Run on Sapphire Rapids"
        default: "1"
      RUN_ZEN_BENCH:
        description: "Run on Zen4"
        default: "0"
      RUN_ADL_BENCH:
        description: "Run on Raptor Lake"
        default: "0"
      RUN_CLX_BENCH:
        description: "Run on Coffee Lake"
        default: "0"
  push:
    branches:
      - 'main'
  pull_request:
    types: [ labeled ]

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh
  NUM_ITER: 100

jobs:
  Check_LLVM:
    if: ${{ github.event_name }} == "push" || \
        (${{ github.event_name }} == "pull_request" && ${{ github.event.label.name == 'benchmark' }})
    uses: ./.github/workflows/tpp-llvm.yml
    secrets: inherit

  TPP-MLIR-SPR-BASE:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_SPR_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && ${{ github.event.label.name == 'benchmark' }})
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Sapphire Rapids Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=spr --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-SPR-OMP:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_SPR_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && ${{ github.event.label.name == 'benchmark' }})
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Sapphire Rapids OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -o"
          ${{ env.SRUN }} --partition=spr --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ZEN-BASE:
    runs-on: pcl-tiergarten
    if: inputs.RUN_ZEN_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen4 Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=zen4 --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ZEN-OMP:
    runs-on: pcl-tiergarten
    if: inputs.RUN_ZEN_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen4 OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -o"
          ${{ env.SRUN }} --partition=zen4 --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-CLX-BASE:
    runs-on: pcl-tiergarten
    if: inputs.RUN_CLX_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Coffee Lake Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=clxap --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-CLX-OMP:
    runs-on: pcl-tiergarten
    if: inputs.RUN_CLX_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Coffee Lake OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -o"
          ${{ env.SRUN }} --partition=clxap --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ADL-BASE:
    runs-on: pcl-tiergarten
    if: inputs.RUN_ADL_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Raptor Lake Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=rpl --time=2:00:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ADL-OMP:
    runs-on: pcl-tiergarten
    if: inputs.RUN_ADL_BENCH == 1
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Raptor Lake OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BUILDKITE_BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/buildkite/benchmark.sh -o"
          ${{ env.SRUN }} --partition=rpl --time=2:00:00 --constraint=\"notrb\" -- $CMD
