name: TPP-MLIR Benchmarks

on:
  workflow_dispatch:
    inputs:
      RUN_EMR_BENCH:
        description: "Run on Emerald Rapids"
        default: "0"
      RUN_ZEN_BENCH:
        description: "Run on Zen5"
        default: "0"
      RUN_CLX_BENCH:
        description: "Run on CLX"
        default: "0"
  push:
    branches:
      - 'main'
  pull_request:
    types: [ labeled, opened, edited ]

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh
  NUM_ITER: 100

jobs:
  Check_LLVM:
    if: ${{ github.event_name }} == "push" || \
        (${{ github.event_name }} == "pull_request" && \
            (contains(github.event.pull_request.labels, 'quick-benchmark') || \
             contains(github.event.pull_request.labels, 'full-benchmark')))
    uses: ./.github/workflows/tpp-llvm.yml
    secrets: inherit

  TPP-MLIR-EMR-BASE:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_EMR_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            (contains(github.event.pull_request.labels, 'quick-benchmark') || \
             contains(github.event.pull_request.labels, 'full-benchmark')))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Emerald Rapids Base
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #        ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
        #   ${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-EMR-OMP:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_EMR_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            (contains(github.event.pull_request.labels, 'quick-benchmark') || \
             contains(github.event.pull_request.labels, 'full-benchmark')))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Emerald Rapids OpenMP
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #        ${{ github.workspace }}/scripts/github/benchmark.sh -o"
        #   ${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ZEN-BASE:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_ZEN_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            contains(github.event.pull_request.labels, 'full-benchmark'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen5 Base
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #        ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
        #   ${{ env.SRUN }} --partition=zen5 --time=0:30:00 -- $CMD

  TPP-MLIR-ZEN-OMP:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_ZEN_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            contains(github.event.pull_request.labels, 'full-benchmark'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen5 OpenMP
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #        ${{ github.workspace }}/scripts/github/benchmark.sh -o"
        #   ${{ env.SRUN }} --partition=zen5 --time=0:30:00 -- $CMD

  TPP-MLIR-CLX-BASE:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_CLX_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            contains(github.event.pull_request.labels, 'full-benchmark'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: CLX Base
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #         ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
        #   ${{ env.SRUN }} --partition=clxap --time=0:30:00 -- $CMD

  TPP-MLIR-CLX-OMP:
    runs-on: pcl-tiergarten
    if: ${{ github.event_name }} == "push" || \
        ${{ inputs.RUN_CLX_BENCH }} == 1 || \
        (${{ github.event_name }} == "pull_request" && \
            contains(github.event.pull_request.labels, 'full-benchmark'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: CLX OpenMP
        run: "echo Hi"
        # run: |-
        #   CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
        #         ${{ github.workspace }}/scripts/github/benchmark.sh -o"
        #   ${{ env.SRUN }} --partition=clxap --time=0:30:00 -- $CMD
        